homeassistant:
  enabled: false
frontend:
  enabled: true
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://$MQTT_HOST:$MQTT_PORT
  user: $MQTT_ADMIN_USER
  password: $MQTT_ADMIN_PASS
serial:
  port: tcp://$SLZB06_IP:$SLZB06_PORT
  adapter: ember
advanced:
  channel: 15
  pan_id: 6754
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  network_key:
    - 73
    - 49
    - 51
    - 21
    - 13
    - 90
    - 81
    - 184
    - 10
    - 137
    - 26
    - 221
    - 131
    - 161
    - 118
    - 123
availability:
  enabled: true
version: 4
