homeassistant:
  enabled: false
frontend:
  enabled: true
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  user: admin
  password: mqtt_admin_password
adapter: zstack
serial:
  port: tcp://zigbee-adapter-sim:6638
advanced:
  channel: 15
  pan_id: 6754
  ext_pan_id:
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
    - 221
  network_key:
    - 199
    - 74
    - 199
    - 234
    - 9
    - 211
    - 117
    - 92
    - 245
    - 49
    - 23
    - 185
    - 95
    - 27
    - 37
    - 182
availability:
  enabled: true
version: 4
