homeassistant: false
permit_join: false
frontend:
  port: 8080

mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  user: admin
  password: mqtt_admin_password

serial:
  port: tcp://192.168.1.50:6638

advanced:
  channel: 15
  pan_id: 0x1A62
  ext_pan_id: [0xDD,0xDD,0xDD,0xDD,0xDD,0xDD,0xDD,0xDD]
  network_key: GENERATE

availability: true
